# Generated by Django 3.0.2 on 2020-02-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
