# Generated by Django 3.0.2 on 2020-01-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
        ('mainapp', '0004_auto_20200120_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generos.Genero'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
