# Generated by Django 3.0.2 on 2020-01-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
        ('mainapp', '0005_auto_20200125_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.Artista'),
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
    ]
