# Generated by Django 3.0.2 on 2020-01-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0001_initial'),
        ('generos', '0001_initial'),
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albuns.Album')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.Artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generos.Genero')),
            ],
        ),
    ]
