# Generated by Django 3.0.2 on 2020-01-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200126_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='album',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musica',
        ),
    ]
